# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: action checkout
    - uses: actions/checkout@v2

    - name: Install NodeJs
      uses: action/strp-node@v2-beta
      with:
        node-version: 12

    - name: Install Yarn
      uses: borales/action-yarn@v2.0.0
      with:
       cmd: install # will run `yarn install` command

    - name: Build React App
      run: yarn build
